import type { NavigationSection } from "~/types/navigation";

export const navigationSections: NavigationSection[] = [
  {
    id: "registros",
    title: "Registros",
    translationKey: "navigation.registros",
    icon: "Building",
    items: [
      {
        id: "registros-sociedades",
        label: "Sociedades",
        translationKey: "navigation.sociedades",
        icon: "Building2",
        hasSubmenu: true,
        submenuItems: [
          {
            id: "sociedades-dashboard",
            label: "Dashboard",
            translationKey: "navigation.dashboard",
            icon: "LayoutDashboard",
            href: "/registros/sociedades/dashboard",
          },
          {
            id: "sociedades-agregar",
            label: "Agregar sociedad",
            translationKey: "navigation.agregarSociedad",
            icon: "FilePlus2",
            href: "/registros/sociedades/agregar",
          },
          {
            id: "sociedades-historial",
            label: "Historial de registros",
            translationKey: "navigation.historialSociedades",
            icon: "History",
            href: "/registros/sociedades/historial",
          },
        ],
        roles: ["admin", "manager", "user"],
      },
      {
        id: "registros-sucursales",
        label: "Sucursales",
        translationKey: "navigation.sucursales",
        icon: "MapPin",
        hasSubmenu: true,
        submenuItems: [
          {
            id: "sucursales-dashboard",
            label: "Dashboard",
            translationKey: "navigation.dashboard",
            icon: "LayoutDashboard",
            href: "/registros/sucursales/dashboard",
          },
          {
            id: "sucursales-agregar",
            label: "Agregar sucursal",
            translationKey: "navigation.agregarSucursal",
            icon: "FilePlus2",
            href: "/registros/sucursales/agregar",
          },
          {
            id: "sucursales-historial",
            label: "Historial de registros",
            translationKey: "navigation.historialSucursales",
            icon: "History",
            href: "/registros/sucursales/historial",
          },
        ],
        roles: ["admin", "manager", "user"],
      },
    ],
  },
  {
    id: "operaciones",
    title: "Operaciones",
    translationKey: "navigation.operaciones",
    icon: "Briefcase",
    items: [
      {
        id: "junta-accionistas",
        label: "Junta de Accionistas",
        translationKey: "navigation.juntaAccionistas",
        icon: "Crown",
        hasSubmenu: true,
        submenuItems: [
          {
            id: "junta-dashboard",
            label: "Dashboard",
            translationKey: "navigation.dashboard",
            icon: "LayoutDashboard",
            href: "/operaciones/junta-accionistas/dashboard",
          },
          {
            id: "junta-crear",
            label: "Crear",
            translationKey: "navigation.crear",
            icon: "FilePlus2",
            href: "/operaciones/junta-accionistas/crear",
          },
          {
            id: "junta-historico",
            label: "Histórico",
            translationKey: "navigation.historico",
            icon: "History",
            href: "/operaciones/junta-accionistas/historico",
          },
        ],
        roles: ["admin"],
      },
      {
        id: "directorio",
        label: "Directorio",
        translationKey: "navigation.directorio",
        icon: "Users",
        hasSubmenu: true,
        submenuItems: [
          {
            id: "directorio-dashboard",
            label: "Dashboard",
            translationKey: "navigation.dashboard",
            icon: "LayoutDashboard",
            href: "/operaciones/directorio/dashboard",
          },
          {
            id: "directorio-crear",
            label: "Crear",
            translationKey: "navigation.crear",
            icon: "FilePlus2",
            href: "/operaciones/directorio/crear",
          },
          {
            id: "directorio-historico",
            label: "Histórico",
            translationKey: "navigation.historico",
            icon: "History",
            href: "/operaciones/directorio/historico",
          },
        ],
        roles: ["admin", "manager"],
      },
    ],
  },
  {
    id: "storage",
    title: "Storage",
    translationKey: "navigation.storage",
    icon: "HardDrive",
    items: [
      {
        id: "almacen",
        label: "Almacén",
        translationKey: "navigation.almacen",
        icon: "Database",
        href: "/storage/almacen",
        roles: ["admin", "manager", "user"],
      },
      {
        id: "documentos-generados",
        label: "Documentos Generados",
        translationKey: "navigation.documentosGenerados",
        icon: "FileText",
        href: "/storage/documentos-generados",
        roles: ["admin", "manager", "user"],
      },
    ],
  },
  {
    id: "espacios-trabajo",
    title: "Espacios de Trabajo",
    translationKey: "navigation.espaciosTrabajo",
    icon: "FolderKanban",
    items: [
      {
        id: "espacios-trabajo-dashboard",
        label: "Dashboard",
        translationKey: "navigation.dashboard",
        icon: "LayoutDashboard",
        href: "/espacios-trabajo/dashboard",
      },
      {
        id: "espacios-trabajo-espacios",
        label: "Espacios",
        translationKey: "navigation.espacios",
        icon: "FolderKanban",
        href: "/espacios-trabajo/espacios",
      },
      {
        id: "espacios-trabajo-crear",
        label: "Crear espacio",
        translationKey: "navigation.crearEspacio",
        icon: "FilePlus2",
        href: "/espacios-trabajo/crear",
      },
    ],
  },
  {
    id: "chat-ia",
    title: "Chat IA",
    translationKey: "navigation.chatIA",
    icon: "Bot",
    items: [
      {
        id: "chat-ia-iniciar",
        label: "Iniciar Chat",
        translationKey: "navigation.iniciarChat",
        icon: "Bot",
        href: "/chat-ia",
        roles: ["admin", "manager", "user"],
      },
    ],
  },
];
