import type { NavigationSection } from "~/types/navigation";

export const navigationSections: NavigationSection[] = [
  {
    id: "registros",
    title: "Registros",
    translationKey: "navigation.registros",
    items: [
      {
        id: "registros-sociedades",
        label: "Sociedades",
        translationKey: "navigation.sociedades",
        icon: "Building2",
        hasSubmenu: true,
        submenuItems: [
          {
            id: "sociedades-dashboard",
            label: "Dashboard",
            translationKey: "navigation.dashboard",
            icon: "LayoutDashboard",
            href: "/registros/sociedades/dashboard",
          },
          {
            id: "sociedades-agregar",
            label: "Agregar sociedad",
            translationKey: "navigation.agregarSociedad",
            icon: "FilePlus2",
            href: "/registros/sociedades/agregar",
          },
          {
            id: "sociedades-historial",
            label: "Historial de registros",
            translationKey: "navigation.historialSociedades",
            icon: "History",
            href: "/registros/sociedades/historial",
          },
        ],
        roles: ["admin", "manager", "user"],
      },
      {
        id: "registros-sucursales",
        label: "Sucursales",
        translationKey: "navigation.sucursales",
        icon: "MapPin",
        hasSubmenu: true,
        submenuItems: [
          {
            id: "sucursales-dashboard",
            label: "Dashboard",
            translationKey: "navigation.dashboard",
            icon: "LayoutDashboard",
            href: "/registros/sucursales/dashboard",
          },
          {
            id: "sucursales-agregar",
            label: "Agregar sucursal",
            translationKey: "navigation.agregarSucursal",
            icon: "FilePlus2",
            href: "/registros/sucursales/agregar",
          },
          {
            id: "sucursales-historial",
            label: "Historial de registros",
            translationKey: "navigation.historialSucursales",
            icon: "History",
            href: "/registros/sucursales/historial",
          },
        ],
        roles: ["admin", "manager", "user"],
      },
    ],
  },
  {
    id: "operaciones",
    title: "Operaciones de Órgano de Control",
    translationKey: "navigation.operaciones",
    items: [
      {
        id: "directorio",
        label: "Directorio",
        translationKey: "navigation.directorio",
        icon: "Users",
        hasSubmenu: true,
        submenuItems: [
          {
            id: "directorio-dashboard",
            label: "Dashboard",
            translationKey: "navigation.dashboard",
            icon: "LayoutDashboard",
            href: "/operaciones/directorio/dashboard",
          },
          {
            id: "directores",
            label: "Directores",
            translationKey: "navigation.directores",
            icon: "UserCheck",
            href: "/operaciones/directorio/directores",
          },
          {
            id: "directorio-historico",
            label: "Histórico",
            translationKey: "navigation.historico",
            icon: "History",
            href: "/operaciones/directorio/historico",
          },
        ],
        roles: ["admin", "manager"],
      },
      {
        id: "gerencia-general",
        label: "Gerencia General",
        translationKey: "navigation.gerenciaGeneral",
        icon: "Briefcase",
        hasSubmenu: true,
        submenuItems: [
          {
            id: "gerencia-dashboard",
            label: "Dashboard",
            translationKey: "navigation.dashboard",
            icon: "LayoutDashboard",
            href: "/operaciones/gerencia-general/dashboard",
          },
          {
            id: "gerentes",
            label: "Gerentes",
            translationKey: "navigation.gerentes",
            icon: "UserCog",
            href: "/operaciones/gerencia-general/gerentes",
          },
          {
            id: "gerencia-historico",
            label: "Histórico",
            translationKey: "navigation.historico",
            icon: "History",
            href: "/operaciones/gerencia-general/historico",
          },
        ],
        roles: ["admin", "manager"],
      },
      {
        id: "junta-accionistas",
        label: "Junta de Accionistas",
        translationKey: "navigation.juntaAccionistas",
        icon: "Crown",
        hasSubmenu: true,
        submenuItems: [
          {
            id: "junta-dashboard",
            label: "Dashboard",
            translationKey: "navigation.dashboard",
            icon: "LayoutDashboard",
            href: "/operaciones/junta-accionistas/dashboard",
          },
          {
            id: "accionistas",
            label: "Accionistas",
            translationKey: "navigation.accionistas",
            icon: "Users2",
            href: "/operaciones/junta-accionistas/accionistas",
          },
          {
            id: "junta-historico",
            label: "Histórico",
            translationKey: "navigation.historico",
            icon: "History",
            href: "/operaciones/junta-accionistas/historico",
          },
        ],
        roles: ["admin"],
      },
    ],
  },
  {
    id: "storage",
    title: "Storage",
    translationKey: "navigation.storage",
    items: [
      {
        id: "almacen",
        label: "Almacén",
        translationKey: "navigation.almacen",
        icon: "Archive",
        href: "/storage/almacen",
        roles: ["admin", "manager", "user"],
      },
      {
        id: "documentos-generados",
        label: "Documentos Generados",
        translationKey: "navigation.documentosGenerados",
        icon: "FileText",
        href: "/storage/documentos-generados",
        roles: ["admin", "manager", "user"],
      },
    ],
  },
  {
    id: "features",
    title: "Features",
    translationKey: "navigation.features",
    items: [
      {
        id: "chat-ia",
        label: "Chat IA",
        translationKey: "navigation.chatIA",
        icon: "MessageCircle",
        href: "/features/chat-ia",
        roles: ["admin", "manager", "user"],
      },
      {
        id: "documentos-ia",
        label: "Documentos IA",
        translationKey: "navigation.documentosIA",
        icon: "FileSearch",
        href: "/features/documentos-ia",
        roles: ["admin", "manager", "user"],
      },
      {
        id: "reporteria",
        label: "Reportería",
        translationKey: "navigation.reporteria",
        icon: "BarChart3",
        href: "/features/reporteria",
        roles: ["admin", "manager"],
      },
    ],
  },
];
