import type { NavigationSection } from "~/types/navigation";

export const navigationSections: NavigationSection[] = [
  {
    id: "registro-societario",
    title: "Registro Societario",
    translationKey: "nav.registroSocietario",
    items: [
      {
        id: "sociedades",
        label: "Sociedades",
        translationKey: "nav.sociedades",
        icon: "Building2",
        href: "/registro-societario/sociedades",
        roles: ["admin", "manager", "user"],
      },
      {
        id: "sucursales",
        label: "Sucursales",
        translationKey: "nav.sucursales",
        icon: "MapPin",
        href: "/registro-societario/sucursales",
        roles: ["admin", "manager", "user"],
      },
    ],
  },
  {
    id: "operaciones",
    title: "Operaciones de Órgano de Control",
    translationKey: "nav.operaciones",
    items: [
      {
        id: "directorio",
        label: "Directorio",
        translationKey: "nav.directorio",
        icon: "Users",
        hasSubmenu: true,
        submenuItems: [
          {
            id: "directorio-dashboard",
            label: "Dashboard",
            translationKey: "nav.dashboard",
            icon: "LayoutDashboard",
            href: "/operaciones/directorio/dashboard",
          },
          {
            id: "directores",
            label: "Directores",
            translationKey: "nav.directores",
            icon: "UserCheck",
            href: "/operaciones/directorio/directores",
          },
          {
            id: "directorio-historico",
            label: "Histórico",
            translationKey: "nav.historico",
            icon: "History",
            href: "/operaciones/directorio/historico",
          },
        ],
        roles: ["admin", "manager"],
      },
      {
        id: "gerencia-general",
        label: "Gerencia General",
        translationKey: "nav.gerenciaGeneral",
        icon: "Briefcase",
        hasSubmenu: true,
        submenuItems: [
          {
            id: "gerencia-dashboard",
            label: "Dashboard",
            translationKey: "nav.dashboard",
            icon: "LayoutDashboard",
            href: "/operaciones/gerencia-general/dashboard",
          },
          {
            id: "gerentes",
            label: "Gerentes",
            translationKey: "nav.gerentes",
            icon: "UserCog",
            href: "/operaciones/gerencia-general/gerentes",
          },
          {
            id: "gerencia-historico",
            label: "Histórico",
            translationKey: "nav.historico",
            icon: "History",
            href: "/operaciones/gerencia-general/historico",
          },
        ],
        roles: ["admin", "manager"],
      },
      {
        id: "junta-accionistas",
        label: "Junta de Accionistas",
        translationKey: "nav.juntaAccionistas",
        icon: "Crown",
        hasSubmenu: true,
        submenuItems: [
          {
            id: "junta-dashboard",
            label: "Dashboard",
            translationKey: "nav.dashboard",
            icon: "LayoutDashboard",
            href: "/operaciones/junta-accionistas/dashboard",
          },
          {
            id: "accionistas",
            label: "Accionistas",
            translationKey: "nav.accionistas",
            icon: "Users2",
            href: "/operaciones/junta-accionistas/accionistas",
          },
          {
            id: "junta-historico",
            label: "Histórico",
            translationKey: "nav.historico",
            icon: "History",
            href: "/operaciones/junta-accionistas/historico",
          },
        ],
        roles: ["admin"],
      },
    ],
  },
  {
    id: "storage",
    title: "Storage",
    translationKey: "nav.storage",
    items: [
      {
        id: "almacen",
        label: "Almacén",
        translationKey: "nav.almacen",
        icon: "Archive",
        href: "/storage/almacen",
        roles: ["admin", "manager", "user"],
      },
      {
        id: "documentos-generados",
        label: "Documentos Generados",
        translationKey: "nav.documentosGenerados",
        icon: "FileText",
        href: "/storage/documentos-generados",
        roles: ["admin", "manager", "user"],
      },
    ],
  },
  {
    id: "features",
    title: "Features",
    translationKey: "nav.features",
    items: [
      {
        id: "chat-ia",
        label: "Chat IA",
        translationKey: "nav.chatIA",
        icon: "MessageCircle",
        href: "/features/chat-ia",
        roles: ["admin", "manager", "user"],
      },
      {
        id: "documentos-ia",
        label: "Documentos IA",
        translationKey: "nav.documentosIA",
        icon: "FileSearch",
        href: "/features/documentos-ia",
        roles: ["admin", "manager", "user"],
      },
      {
        id: "reporteria",
        label: "Reportería",
        translationKey: "nav.reporteria",
        icon: "BarChart3",
        href: "/features/reporteria",
        roles: ["admin", "manager"],
      },
    ],
  },
];
