import {
  Archive,
  ArrowLeft,
  ArrowRight,
  BarChart3,
  Bot,
  Briefcase,
  Building,
  Building2,
  Calendar,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Crown,
  Database,
  Download,
  EllipsisVertical,
  FileCheck,
  FilePlus2,
  FileSearch,
  FileText,
  FolderKanban,
  HardDrive,
  HelpCircle,
  History,
  Languages,
  LayoutDashboard,
  LoaderCircle,
  LogOut,
  MapPin,
  Menu,
  MessageCircle,
  Monitor,
  Moon,
  MoreHorizontal,
  Package,
  Palette,
  Plus,
  Search,
  Settings,
  SquarePen,
  Sun,
  TextAlignJustify,
  Trash2,
  User,
  UserCheck,
  UserCog,
  UserRoundPlus,
  Users,
  Users2,
  Vault,
  X,
} from "lucide-vue-next";

// Tipo para componentes Lucide
type IconValue = any;

// Mapa de componentes Lucide
const iconMap: Record<string, IconValue> = {
  Building2,
  Building,
  Vault,
  MapPin,
  Users,
  LayoutDashboard,
  UserCheck,
  History,
  Briefcase,
  UserCog,
  Crown,
  Users2,
  Archive,
  FileText,
  MessageCircle,
  FileSearch,
  BarChart3,
  Package,
  Palette,
  Settings,
  HelpCircle,
  Menu,
  X,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  LogOut,
  User,
  Languages,
  Sun,
  Moon,
  Monitor,
  SquarePen,
  Trash2,
  Download,
  Plus,
  ArrowLeft,
  ArrowRight,
  LoaderCircle,
  Search,
  Calendar,
  Check,
  FileCheck,
  FilePlus2,
  UserRoundPlus,
  EllipsisVertical,
  MoreHorizontal,
  TextAlignJustify,
  Database,
  HardDrive,
  FolderKanban,
  Bot,
};

/**
 * Obtiene un icono de Lucide
 *
 * @param iconName - Nombre del componente Lucide (ej: "Users", "Settings")
 * @returns Componente Vue de lucide-vue-next o null si no existe
 *
 * @example
 * getIcon("Users") → Componente Vue de lucide-vue-next
 * getIcon("Settings") → Componente Vue de lucide-vue-next
 */
export const getIcon = (iconName: string): IconValue | null => {
  return iconMap[iconName] || null;
};
