import type { Language } from "~/types/user";

// Mock translations - en producción usar @nuxtjs/i18n
const translations = {
  es: {
    "nav.registroSocietario": "Registro Societario",
    "nav.sociedades": "Sociedades",
    "nav.sucursales": "Sucursales",
    "nav.operaciones": "Operaciones de Órgano de Control",
    "nav.directorio": "Directorio",
    "nav.gerenciaGeneral": "Gerencia General",
    "nav.juntaAccionistas": "Junta de Accionistas",
    "nav.dashboard": "Dashboard",
    "nav.directores": "Directores",
    "nav.gerentes": "Gerentes",
    "nav.accionistas": "Accionistas",
    "nav.historico": "Histórico",
    "nav.storage": "Storage",
    "nav.almacen": "Almacén",
    "nav.documentosGenerados": "Documentos Generados",
    "nav.features": "Features",
    "nav.chatIA": "Chat IA",
    "nav.documentosIA": "Documentos IA",
    "nav.reporteria": "Reportería",
    "nav.planServicio": "Plan de Servicio",
    "nav.personalizacion": "Personalización",
    "nav.configuracion": "Configuración",
    "nav.ayuda": "Ayuda",
    "user.profile": "Perfil",
    "user.settings": "Configuración",
    "user.logout": "Cerrar Sesión",
    "common.collapse": "Colapsar",
    "common.expand": "Expandir",
    "common.cancel": "Cancelar",
    "common.save": "Guardar Cambios",
    "common.new": "Nuevo",
    "theme.light": "Claro",
    "theme.dark": "Oscuro",
    "theme.system": "Sistema",
    "theme.current": "Tema actual",
    "theme.systemFollow": "siguiendo preferencia del sistema",
    "language.current": "Idioma actual",
    "config.appearance": "Apariencia",
    "config.appearanceDesc": "Personaliza el tema de la aplicación",
    "config.language": "Idioma",
    "config.languageDesc": "Selecciona tu idioma preferido",
    "config.notifications": "Notificaciones",
    "config.notificationsDesc": "Configura tus preferencias de notificaciones",
    "config.emailNotifications": "Notificaciones por email",
    "config.pushNotifications": "Notificaciones push",
    "config.modalTitle": "Configuración",
    "config.modalDesc": "Personaliza tu experiencia en PROBO",
    "config.administration": "Administración",
    "config.personal": "Personal",
    "config.integrations": "Integraciones",
    "config.dashboard": "Dashboard",
    "config.adminDashboard": "Dashboard de Administración",
    "config.adminDashboardDesc": "Configura el panel de administración",
    "config.dashboardSettings": "Configuración de Dashboard",
    "config.dashboardSettingsDesc": "Personaliza tu panel de control principal",
    "config.billing": "Facturación",
    "config.billingDesc": "Gestiona la facturación y pagos",
    "config.billingSettings": "Configuración de Facturación",
    "config.billingSettingsDesc": "Administra métodos de pago y planes",
    "config.users": "Usuarios",
    "config.usersDesc": "Administra usuarios del sistema",
    "config.userSettings": "Gestión de Usuarios",
    "config.userSettingsDesc": "Crear, editar y administrar usuarios",
    "config.general": "General",
    "config.generalDesc": "Configuraciones generales del sistema",
    "config.generalSettings": "Configuraciones Generales",
    "config.generalSettingsDesc": "Ajustes básicos de la aplicación",
    "config.preferences": "Preferencias",
    "config.preferencesDesc": "Personaliza tu experiencia de usuario",
    "config.profile": "Perfil",
    "config.profileDesc": "Administra tu información personal",
    "config.profileSettings": "Configuración de Perfil",
    "config.profileSettingsDesc": "Actualiza tu información y preferencias",
    "config.gmail": "Gmail",
    "config.gmailDesc": "Integración con Gmail",
    "config.gmailIntegration": "Integración Gmail",
    "config.gmailIntegrationDesc":
      "Conecta tu cuenta de Gmail para sincronizar emails",
    "config.connectGmail": "Conectar Gmail",
    "config.googleDrive": "Google Drive",
    "config.googleDriveDesc": "Integración con Google Drive",
    "config.googleDriveIntegration": "Integración Google Drive",
    "config.googleDriveIntegrationDesc":
      "Conecta Google Drive para almacenar documentos",
    "config.connectGoogleDrive": "Conectar Google Drive",
    "dashboard.title": "Dashboard PROBO",
    "dashboard.subtitle":
      "Bienvenido a tu plataforma de gestión legal corporativa",
    "dashboard.sociedadesRegistradas": "Sociedades Registradas",
    "dashboard.documentosGenerados": "Documentos Generados",
    "dashboard.usuariosActivos": "Usuarios Activos",
    "dashboard.consultasIA": "Consultas IA",
    "dashboard.actividadReciente": "Actividad Reciente",
    "dashboard.accesosRapidos": "Accesos Rápidos",
    "dashboard.funcionesMasUsadas": "Funciones más utilizadas",
    "dashboard.nuevaSociedad": "Nueva Sociedad",
    "dashboard.consultarIA": "Consultar IA",
    "dashboard.verDocumentos": "Ver Documentos",
  },
  en: {
    "nav.registroSocietario": "Corporate Registry",
    "nav.sociedades": "Companies",
    "nav.sucursales": "Branches",
    "nav.operaciones": "Control Body Operations",
    "nav.directorio": "Board",
    "nav.gerenciaGeneral": "General Management",
    "nav.juntaAccionistas": "Shareholders Meeting",
    "nav.dashboard": "Dashboard",
    "nav.directores": "Directors",
    "nav.gerentes": "Managers",
    "nav.accionistas": "Shareholders",
    "nav.historico": "History",
    "nav.storage": "Storage",
    "nav.almacen": "Warehouse",
    "nav.documentosGenerados": "Generated Documents",
    "nav.features": "Features",
    "nav.chatIA": "AI Chat",
    "nav.documentosIA": "AI Documents",
    "nav.reporteria": "Reporting",
    "nav.planServicio": "Service Plan",
    "nav.personalizacion": "Customization",
    "nav.configuracion": "Settings",
    "nav.ayuda": "Help",
    "user.profile": "Profile",
    "user.settings": "Settings",
    "user.logout": "Logout",
    "common.collapse": "Collapse",
    "common.expand": "Expand",
    "common.cancel": "Cancel",
    "common.save": "Save Changes",
    "common.new": "New",
    "theme.light": "Light",
    "theme.dark": "Dark",
    "theme.system": "System",
    "theme.current": "Current theme",
    "theme.systemFollow": "following system preference",
    "language.current": "Current language",
    "config.appearance": "Appearance",
    "config.appearanceDesc": "Customize application theme",
    "config.language": "Language",
    "config.languageDesc": "Select your preferred language",
    "config.notifications": "Notifications",
    "config.notificationsDesc": "Configure your notification preferences",
    "config.emailNotifications": "Email notifications",
    "config.pushNotifications": "Push notifications",
    "config.modalTitle": "Settings",
    "config.modalDesc": "Customize your PROBO experience",
    "config.administration": "Administration",
    "config.personal": "Personal",
    "config.integrations": "Integrations",
    "config.dashboard": "Dashboard",
    "config.adminDashboard": "Administration Dashboard",
    "config.adminDashboardDesc": "Configure the administration panel",
    "config.dashboardSettings": "Dashboard Settings",
    "config.dashboardSettingsDesc": "Customize your main control panel",
    "config.billing": "Billing",
    "config.billingDesc": "Manage billing and payments",
    "config.billingSettings": "Billing Settings",
    "config.billingSettingsDesc": "Manage payment methods and plans",
    "config.users": "Users",
    "config.usersDesc": "Manage system users",
    "config.userSettings": "User Management",
    "config.userSettingsDesc": "Create, edit and manage users",
    "config.general": "General",
    "config.generalDesc": "General system settings",
    "config.generalSettings": "General Settings",
    "config.generalSettingsDesc": "Basic application settings",
    "config.preferences": "Preferences",
    "config.preferencesDesc": "Customize your user experience",
    "config.profile": "Profile",
    "config.profileDesc": "Manage your personal information",
    "config.profileSettings": "Profile Settings",
    "config.profileSettingsDesc": "Update your information and preferences",
    "config.gmail": "Gmail",
    "config.gmailDesc": "Gmail integration",
    "config.gmailIntegration": "Gmail Integration",
    "config.gmailIntegrationDesc": "Connect your Gmail account to sync emails",
    "config.connectGmail": "Connect Gmail",
    "config.googleDrive": "Google Drive",
    "config.googleDriveDesc": "Google Drive integration",
    "config.googleDriveIntegration": "Google Drive Integration",
    "config.googleDriveIntegrationDesc":
      "Connect Google Drive to store documents",
    "config.connectGoogleDrive": "Connect Google Drive",
    "dashboard.title": "PROBO Dashboard",
    "dashboard.subtitle": "Welcome to your corporate legal management platform",
    "dashboard.sociedadesRegistradas": "Registered Companies",
    "dashboard.documentosGenerados": "Generated Documents",
    "dashboard.usuariosActivos": "Active Users",
    "dashboard.consultasIA": "AI Queries",
    "dashboard.actividadReciente": "Recent Activity",
    "dashboard.accesosRapidos": "Quick Access",
    "dashboard.funcionesMasUsadas": "Most used functions",
    "dashboard.nuevaSociedad": "New Company",
    "dashboard.consultarIA": "Ask AI",
    "dashboard.verDocumentos": "View Documents",
  },
};

export const useLanguage = () => {
  const currentLanguage = ref<Language>("es");

  // Inicializar idioma desde localStorage al montar
  onMounted(() => {
    const stored = localStorage.getItem("probo-language") as Language;
    if (stored && ["es", "en", "pt", "fr", "de"].includes(stored)) {
      currentLanguage.value = stored;
    }
  });

  // Función para traducir texto
  const t = (key: string): string => {
    const langTranslations =
      translations[currentLanguage.value as keyof typeof translations] ||
      translations.es;
    return langTranslations[key as keyof typeof langTranslations] || key;
  };

  // Cambiar idioma
  const setLanguage = (language: Language) => {
    currentLanguage.value = language;

    if (import.meta.client) {
      localStorage.setItem("probo-language", language);
    }
  };

  // Lista de idiomas disponibles
  const availableLanguages = [
    { code: "es", name: "Español", flag: "🇪🇸" },
    { code: "en", name: "English", flag: "🇺🇸" },
    { code: "pt", name: "Português", flag: "🇧🇷" },
    { code: "fr", name: "Français", flag: "🇫🇷" },
    { code: "de", name: "Deutsch", flag: "🇩🇪" },
  ];

  return {
    currentLanguage: readonly(currentLanguage),
    availableLanguages,
    t,
    setLanguage,
  };
};
