/**
 * Enum para contextos de votación
 * Identifica qué punto de agenda se está votando
 */
export enum VoteContext {
  AUMENTO_CAPITAL = "AUMENTO_CAPITAL",
  APORTES_DINERARIOS = "APORTES_DINERARIOS",
  CAPITALIZACION_DE_CREDITOS = "CAPITALIZACION_DE_CREDITOS",
  REMOCION_DIRECTORES = "REMOCION_DIRECTORES",
  DESIGNACION_DIRECTORES = "DESIGNACION_DIRECTORES",
  REMOCION_GERENTE = "REMOCION_GERENTE",
  DESIGNACION_GERENTE = "DESIGNACION_GERENTE",
  DIVIDENDOS = "DIVIDENDOS",
}


