import type { TypeOption } from "~/types/TypeOptions";

export const countriesOptions: TypeOption[] = [
  { id: 1, label: "Afganistán", name: "Afganistán", value: "AFG", acronimo: "AFG" },
  { id: 2, label: "Angola", name: "Angola", value: "AGO", acronimo: "AGO" },
  { id: 3, label: "Albania", name: "Albania", value: "ALB", acronimo: "ALB" },
  { id: 4, label: "Andorra", name: "Andorra", value: "AND", acronimo: "AND" },
  {
    id: 5,
    label: "Emiratos Árabes Unidos",
    name: "Emiratos Árabes Unidos",
    value: "ARE",
    acronimo: "ARE",
  },
  { id: 6, label: "Argentina", name: "Argentina", value: "ARG", acronimo: "ARG" },
  { id: 7, label: "Armenia", name: "Armenia", value: "ARM", acronimo: "ARM" },
  { id: 8, label: "Australia", name: "Australia", value: "AUS", acronimo: "AUS" },
  { id: 9, label: "Austria", name: "Austria", value: "AUT", acronimo: "AUT" },
  { id: 10, label: "Azerbaiyán", name: "Azerbaiyán", value: "AZE", acronimo: "AZE" },
  { id: 11, label: "Burkina Faso", name: "Burkina Faso", value: "BFA", acronimo: "BFA" },
  { id: 12, label: "Bangladés", name: "Bangladés", value: "BGD", acronimo: "BGD" },
  { id: 13, label: "Bulgaria", name: "Bulgaria", value: "BGR", acronimo: "BGR" },
  { id: 14, label: "Baréin", name: "Baréin", value: "BHR", acronimo: "BHR" },
  { id: 15, label: "Bahamas", name: "Bahamas", value: "BHS", acronimo: "BHS" },
  {
    id: 16,
    label: "Bosnia y Herzegovina",
    name: "Bosnia y Herzegovina",
    value: "BIH",
    acronimo: "BIH",
  },
  { id: 17, label: "Bielorrusia", name: "Bielorrusia", value: "BLR", acronimo: "BLR" },
  { id: 18, label: "Belice", name: "Belice", value: "BLZ", acronimo: "BLZ" },
  { id: 19, label: "Bolivia", name: "Bolivia", value: "BOL", acronimo: "BOL" },
  { id: 20, label: "Brasil", name: "Brasil", value: "BRA", acronimo: "BRA" },
  { id: 21, label: "Brunéi", name: "Brunéi", value: "BRN", acronimo: "BRN" },
  { id: 22, label: "Botsuana", name: "Botsuana", value: "BWA", acronimo: "BWA" },
  {
    id: 23,
    label: "República Centroafricana",
    name: "República Centroafricana",
    value: "CAF",
    acronimo: "CAF",
  },
  { id: 24, label: "Canadá", name: "Canadá", value: "CAN", acronimo: "CAN" },
  { id: 25, label: "Suiza", name: "Suiza", value: "CHE", acronimo: "CHE" },
  { id: 26, label: "Chile", name: "Chile", value: "CHL", acronimo: "CHL" },
  { id: 27, label: "China", name: "China", value: "CHN", acronimo: "CHN" },
  { id: 28, label: "Costa de Marfil", name: "Costa de Marfil", value: "CIV", acronimo: "CIV" },
  { id: 29, label: "Camerún", name: "Camerún", value: "CMR", acronimo: "CMR" },
  {
    id: 30,
    label: "República Democrática del Congo",
    name: "República Democrática del Congo",
    value: "COD",
    acronimo: "COD",
  },
  { id: 31, label: "Colombia", name: "Colombia", value: "COL", acronimo: "COL" },
  { id: 32, label: "Costa Rica", name: "Costa Rica", value: "CRI", acronimo: "CRI" },
  { id: 33, label: "Cuba", name: "Cuba", value: "CUB", acronimo: "CUB" },
  { id: 34, label: "Chipre", name: "Chipre", value: "CYP", acronimo: "CYP" },
  { id: 35, label: "República Checa", name: "República Checa", value: "CZE", acronimo: "CZE" },
  { id: 36, label: "Alemania", name: "Alemania", value: "DEU", acronimo: "DEU" },
  { id: 37, label: "Yibuti", name: "Yibuti", value: "DJI", acronimo: "DJI" },
  { id: 38, label: "Dinamarca", name: "Dinamarca", value: "DNK", acronimo: "DNK" },
  {
    id: 39,
    label: "República Dominicana",
    name: "República Dominicana",
    value: "DOM",
    acronimo: "DOM",
  },
  { id: 40, label: "Argelia", name: "Argelia", value: "DZA", acronimo: "DZA" },
  { id: 41, label: "Ecuador", name: "Ecuador", value: "ECU", acronimo: "ECU" },
  { id: 42, label: "Egipto", name: "Egipto", value: "EGY", acronimo: "EGY" },
  { id: 43, label: "Eritrea", name: "Eritrea", value: "ERI", acronimo: "ERI" },
  { id: 44, label: "España", name: "España", value: "ESP", acronimo: "ESP" },
  { id: 45, label: "Estonia", name: "Estonia", value: "EST", acronimo: "EST" },
  { id: 46, label: "Etiopía", name: "Etiopía", value: "ETH", acronimo: "ETH" },
  { id: 47, label: "Finlandia", name: "Finlandia", value: "FIN", acronimo: "FIN" },
  { id: 48, label: "Fiyi", name: "Fiyi", value: "FJI", acronimo: "FJI" },
  { id: 49, label: "Francia", name: "Francia", value: "FRA", acronimo: "FRA" },
  { id: 50, label: "Gabón", name: "Gabón", value: "GAB", acronimo: "GAB" },
  { id: 51, label: "Gambia", name: "Gambia", value: "GAM", acronimo: "GAM" },
  { id: 52, label: "Reino Unido", name: "Reino Unido", value: "GBR", acronimo: "GBR" },
  { id: 53, label: "Ghana", name: "Ghana", value: "GHA", acronimo: "GHA" },
  { id: 54, label: "Guinea-Bisáu", name: "Guinea-Bisáu", value: "GNB", acronimo: "GNB" },
  {
    id: 55,
    label: "Guinea Ecuatorial",
    name: "Guinea Ecuatorial",
    value: "GNQ",
    acronimo: "GNQ",
  },
  { id: 56, label: "Grecia", name: "Grecia", value: "GRC", acronimo: "GRC" },
  { id: 57, label: "Granada", name: "Granada", value: "GRD", acronimo: "GRD" },
  { id: 58, label: "Guatemala", name: "Guatemala", value: "GTM", acronimo: "GTM" },
  { id: 59, label: "Guam", name: "Guam", value: "GUM", acronimo: "GUM" },
  { id: 60, label: "Guyana", name: "Guyana", value: "GUY", acronimo: "GUY" },
  { id: 61, label: "Honduras", name: "Honduras", value: "HND", acronimo: "HND" },
  { id: 62, label: "Croacia", name: "Croacia", value: "HRV", acronimo: "HRV" },
  { id: 63, label: "Haití", name: "Haití", value: "HTI", acronimo: "HTI" },
  { id: 64, label: "Hungría", name: "Hungría", value: "HUN", acronimo: "HUN" },
  { id: 65, label: "Indonesia", name: "Indonesia", value: "IDN", acronimo: "IDN" },
  { id: 66, label: "Irlanda", name: "Irlanda", value: "IRL", acronimo: "IRL" },
  { id: 67, label: "Irán", name: "Irán", value: "IRN", acronimo: "IRN" },
  { id: 68, label: "Irak", name: "Irak", value: "IRQ", acronimo: "IRQ" },
  { id: 69, label: "Islandia", name: "Islandia", value: "ISL", acronimo: "ISL" },
  { id: 70, label: "Israel", name: "Israel", value: "ISR", acronimo: "ISR" },
  { id: 71, label: "Italia", name: "Italia", value: "ITA", acronimo: "ITA" },
  { id: 72, label: "Jamaica", name: "Jamaica", value: "JAM", acronimo: "JAM" },
  { id: 73, label: "Japón", name: "Japón", value: "JPN", acronimo: "JPN" },
  { id: 74, label: "Jordania", name: "Jordania", value: "JOR", acronimo: "JOR" },
  { id: 75, label: "Kazajistán", name: "Kazajistán", value: "KAZ", acronimo: "KAZ" },
  { id: 76, label: "Kenia", name: "Kenia", value: "KEN", acronimo: "KEN" },
  { id: 77, label: "Kirguistán", name: "Kirguistán", value: "KGZ", acronimo: "KGZ" },
  { id: 78, label: "Camboya", name: "Camboya", value: "KHM", acronimo: "KHM" },
  { id: 79, label: "Kiribati", name: "Kiribati", value: "KIR", acronimo: "KIR" },
  {
    id: 80,
    label: "San Cristóbal y Nieves",
    name: "San Cristóbal y Nieves",
    value: "KNA",
    acronimo: "KNA",
  },
  { id: 81, label: "Corea del Sur", name: "Corea del Sur", value: "KOR", acronimo: "KOR" },
  { id: 82, label: "Kuwait", name: "Kuwait", value: "KWT", acronimo: "KWT" },
  { id: 83, label: "Laos", name: "Laos", value: "LAO", acronimo: "LAO" },
  { id: 84, label: "Líbano", name: "Líbano", value: "LBN", acronimo: "LBN" },
  { id: 85, label: "Liberia", name: "Liberia", value: "LBR", acronimo: "LBR" },
  { id: 86, label: "Libia", name: "Libia", value: "LBY", acronimo: "LBY" },
  { id: 87, label: "Sri Lanka", name: "Sri Lanka", value: "LKA", acronimo: "LKA" },
  { id: 88, label: "Lesoto", name: "Lesoto", value: "LSO", acronimo: "LSO" },
  { id: 89, label: "Lituania", name: "Lituania", value: "LTU", acronimo: "LTU" },
  { id: 90, label: "Luxemburgo", name: "Luxemburgo", value: "LUX", acronimo: "LUX" },
  { id: 91, label: "Madagascar", name: "Madagascar", value: "MDG", acronimo: "MDG" },
  { id: 92, label: "Maldivas", name: "Maldivas", value: "MDV", acronimo: "MDV" },
  { id: 93, label: "México", name: "México", value: "MEX", acronimo: "MEX" },
  { id: 94, label: "Islas Marshall", name: "Islas Marshall", value: "MHL", acronimo: "MHL" },
  {
    id: 95,
    label: "Macedonia del Norte",
    name: "Macedonia del Norte",
    value: "MKD",
    acronimo: "MKD",
  },
  { id: 96, label: "Mali", name: "Mali", value: "MLI", acronimo: "MLI" },
  { id: 97, label: "Malta", name: "Malta", value: "MLT", acronimo: "MLT" },
  { id: 98, label: "Mauritania", name: "Mauritania", value: "MRT", acronimo: "MRT" },
  { id: 99, label: "Mauricio", name: "Mauricio", value: "MUS", acronimo: "MUS" },
  { id: 100, label: "Malaui", name: "Malaui", value: "MWI", acronimo: "MWI" },
  { id: 101, label: "Malasia", name: "Malasia", value: "MYS", acronimo: "MYS" },
  { id: 102, label: "Namibia", name: "Namibia", value: "NAM", acronimo: "NAM" },
  {
    id: 103,
    label: "Nueva Caledonia",
    name: "Nueva Caledonia",
    value: "NCL",
    acronimo: "NCL",
  },
  { id: 104, label: "Níger", name: "Níger", value: "NER", acronimo: "NER" },
  { id: 105, label: "Nigeria", name: "Nigeria", value: "NGA", acronimo: "NGA" },
  { id: 106, label: "Nicaragua", name: "Nicaragua", value: "NIC", acronimo: "NIC" },
  { id: 107, label: "Países Bajos", name: "Países Bajos", value: "NLD", acronimo: "NLD" },
  { id: 108, label: "Noruega", name: "Noruega", value: "NOR", acronimo: "NOR" },
  { id: 109, label: "Nepal", name: "Nepal", value: "NPL", acronimo: "NPL" },
  { id: 110, label: "Nueva Zelanda", name: "Nueva Zelanda", value: "NZL", acronimo: "NZL" },
  { id: 111, label: "Omán", name: "Omán", value: "OMN", acronimo: "OMN" },
  { id: 112, label: "Pakistán", name: "Pakistán", value: "PAK", acronimo: "PAK" },
  { id: 113, label: "Panamá", name: "Panamá", value: "PAN", acronimo: "PAN" },
  {
    id: 114,
    label: "Papúa Nueva Guinea",
    name: "Papúa Nueva Guinea",
    value: "PNG",
    acronimo: "PNG",
  },
  { id: 115, label: "Polonia", name: "Polonia", value: "POL", acronimo: "POL" },
  { id: 116, label: "Portugal", name: "Portugal", value: "PRT", acronimo: "PRT" },
  { id: 117, label: "Catar", name: "Catar", value: "QAT", acronimo: "QAT" },
  { id: 118, label: "Rumania", name: "Rumania", value: "ROU", acronimo: "ROU" },
  { id: 119, label: "Rusia", name: "Rusia", value: "RUS", acronimo: "RUS" },
  { id: 120, label: "Ruanda", name: "Ruanda", value: "RWA", acronimo: "RWA" },
  { id: 121, label: "Arabia Saudita", name: "Arabia Saudita", value: "SAU", acronimo: "SAU" },
  { id: 122, label: "Senegal", name: "Senegal", value: "SEN", acronimo: "SEN" },
  { id: 123, label: "Singapur", name: "Singapur", value: "SGP", acronimo: "SGP" },
  { id: 124, label: "Sierra Leona", name: "Sierra Leona", value: "SLE", acronimo: "SLE" },
  { id: 125, label: "El Salvador", name: "El Salvador", value: "SLV", acronimo: "SLV" },
  { id: 126, label: "San Marino", name: "San Marino", value: "SMR", acronimo: "SMR" },
  { id: 127, label: "Somalia", name: "Somalia", value: "SOM", acronimo: "SOM" },
  { id: 128, label: "Surinam", name: "Surinam", value: "SUR", acronimo: "SUR" },
  { id: 129, label: "Eslovaquia", name: "Eslovaquia", value: "SVK", acronimo: "SVK" },
  { id: 130, label: "Eslovenia", name: "Eslovenia", value: "SVN", acronimo: "SVN" },
  { id: 131, label: "Suecia", name: "Suecia", value: "SWE", acronimo: "SWE" },
  { id: 132, label: "Esuatini", name: "Esuatini", value: "SWZ", acronimo: "SWZ" },
  { id: 133, label: "Togo", name: "Togo", value: "TGO", acronimo: "TGO" },
  { id: 134, label: "Tailandia", name: "Tailandia", value: "THA", acronimo: "THA" },
  { id: 135, label: "Tayikistán", name: "Tayikistán", value: "TJK", acronimo: "TJK" },
  { id: 136, label: "Timor Oriental", name: "Timor Oriental", value: "TLS", acronimo: "TLS" },
  { id: 137, label: "Turquía", name: "Turquía", value: "TUR", acronimo: "TUR" },
  {
    id: 138,
    label: "Trinidad y Tobago",
    name: "Trinidad y Tobago",
    value: "TTO",
    acronimo: "TTO",
  },
  { id: 139, label: "Taiwán", name: "Taiwán", value: "TWN", acronimo: "TWN" },
  { id: 140, label: "Túnez", name: "Túnez", value: "TUN", acronimo: "TUN" },
  { id: 141, label: "Ucrania", name: "Ucrania", value: "UKR", acronimo: "UKR" },
  { id: 142, label: "Estados Unidos", name: "Estados Unidos", value: "USA", acronimo: "USA" },
  { id: 143, label: "Uruguay", name: "Uruguay", value: "URY", acronimo: "URY" },
  { id: 144, label: "Uzbekistán", name: "Uzbekistán", value: "UZB", acronimo: "UZB" },
  { id: 145, label: "Vanuatu", name: "Vanuatu", value: "VUT", acronimo: "VUT" },
  { id: 146, label: "Venezuela", name: "Venezuela", value: "VEN", acronimo: "VEN" },
  { id: 147, label: "Vietnam", name: "Vietnam", value: "VNM", acronimo: "VNM" },
  { id: 148, label: "Perú", name: "Perú", value: "PER", acronimo: "PER" },
];
