export const countriesOptions = [
  { id: 1, label: "Afganistán", value: "AFG" },
  { id: 2, label: "Angola", value: "AGO" },
  { id: 3, label: "Albania", value: "ALB" },
  { id: 4, label: "Andorra", value: "AND" },
  { id: 5, label: "Emiratos Árabes Unidos", value: "ARE" },
  { id: 6, label: "Argentina", value: "ARG" },
  { id: 7, label: "Armenia", value: "ARM" },
  { id: 8, label: "Australia", value: "AUS" },
  { id: 9, label: "Austria", value: "AUT" },
  { id: 10, label: "Azerbaiyán", value: "AZE" },
  { id: 11, label: "Burkina Faso", value: "BFA" },
  { id: 12, label: "Bangladés", value: "BGD" },
  { id: 13, label: "Bulgaria", value: "BGR" },
  { id: 14, label: "Baréin", value: "BHR" },
  { id: 15, label: "Bahamas", value: "BHS" },
  { id: 16, label: "Bosnia y Herzegovina", value: "BIH" },
  { id: 17, label: "Bielorrusia", value: "BLR" },
  { id: 18, label: "Belice", value: "BLZ" },
  { id: 19, label: "Bolivia", value: "BOL" },
  { id: 20, label: "Brasil", value: "BRA" },
  { id: 21, label: "Brunéi", value: "BRN" },
  { id: 22, label: "Botsuana", value: "BWA" },
  { id: 23, label: "República Centroafricana", value: "CAF" },
  { id: 24, label: "Canadá", value: "CAN" },
  { id: 25, label: "Suiza", value: "CHE" },
  { id: 26, label: "Chile", value: "CHL" },
  { id: 27, label: "China", value: "CHN" },
  { id: 28, label: "Costa de Marfil", value: "CIV" },
  { id: 29, label: "Camerún", value: "CMR" },
  { id: 30, label: "República Democrática del Congo", value: "COD" },
  { id: 31, label: "Colombia", value: "COL" },
  { id: 32, label: "Costa Rica", value: "CRI" },
  { id: 33, label: "Cuba", value: "CUB" },
  { id: 34, label: "Chipre", value: "CYP" },
  { id: 35, label: "República Checa", value: "CZE" },
  { id: 36, label: "Alemania", value: "DEU" },
  { id: 37, label: "Yibuti", value: "DJI" },
  { id: 38, label: "Dinamarca", value: "DNK" },
  { id: 39, label: "República Dominicana", value: "DOM" },
  { id: 40, label: "Argelia", value: "DZA" },
  { id: 41, label: "Ecuador", value: "ECU" },
  { id: 42, label: "Egipto", value: "EGY" },
  { id: 43, label: "Eritrea", value: "ERI" },
  { id: 44, label: "España", value: "ESP" },
  { id: 45, label: "Estonia", value: "EST" },
  { id: 46, label: "Etiopía", value: "ETH" },
  { id: 47, label: "Finlandia", value: "FIN" },
  { id: 48, label: "Fiyi", value: "FJI" },
  { id: 49, label: "Francia", value: "FRA" },
  { id: 50, label: "Gabón", value: "GAB" },
  { id: 51, label: "Gambia", value: "GAM" },
  { id: 52, label: "Reino Unido", value: "GBR" },
  { id: 53, label: "Ghana", value: "GHA" },
  { id: 54, label: "Guinea-Bisáu", value: "GNB" },
  { id: 55, label: "Guinea Ecuatorial", value: "GNQ" },
  { id: 56, label: "Grecia", value: "GRC" },
  { id: 57, label: "Granada", value: "GRD" },
  { id: 58, label: "Guatemala", value: "GTM" },
  { id: 59, label: "Guam", value: "GUM" },
  { id: 60, label: "Guyana", value: "GUY" },
  { id: 61, label: "Honduras", value: "HND" },
  { id: 62, label: "Croacia", value: "HRV" },
  { id: 63, label: "Haití", value: "HTI" },
  { id: 64, label: "Hungría", value: "HUN" },
  { id: 65, label: "Indonesia", value: "IDN" },
  { id: 66, label: "Irlanda", value: "IRL" },
  { id: 67, label: "Irán", value: "IRN" },
  { id: 68, label: "Irak", value: "IRQ" },
  { id: 69, label: "Islandia", value: "ISL" },
  { id: 70, label: "Israel", value: "ISR" },
  { id: 71, label: "Italia", value: "ITA" },
  { id: 72, label: "Jamaica", value: "JAM" },
  { id: 73, label: "Japón", value: "JPN" },
  { id: 74, label: "Jordania", value: "JOR" },
  { id: 75, label: "Kazajistán", value: "KAZ" },
  { id: 76, label: "Kenia", value: "KEN" },
  { id: 77, label: "Kirguistán", value: "KGZ" },
  { id: 78, label: "Camboya", value: "KHM" },
  { id: 79, label: "Kiribati", value: "KIR" },
  { id: 80, label: "San Cristóbal y Nieves", value: "KNA" },
  { id: 81, label: "Corea del Sur", value: "KOR" },
  { id: 82, label: "Kuwait", value: "KWT" },
  { id: 83, label: "Laos", value: "LAO" },
  { id: 84, label: "Líbano", value: "LBN" },
  { id: 85, label: "Liberia", value: "LBR" },
  { id: 86, label: "Libia", value: "LBY" },
  { id: 87, label: "Sri Lanka", value: "LKA" },
  { id: 88, label: "Lesoto", value: "LSO" },
  { id: 89, label: "Lituania", value: "LTU" },
  { id: 90, label: "Luxemburgo", value: "LUX" },
  { id: 91, label: "Madagascar", value: "MDG" },
  { id: 92, label: "Maldivas", value: "MDV" },
  { id: 93, label: "México", value: "MEX" },
  { id: 94, label: "Islas Marshall", value: "MHL" },
  { id: 95, label: "Macedonia del Norte", value: "MKD" },
  { id: 96, label: "Mali", value: "MLI" },
  { id: 97, label: "Malta", value: "MLT" },
  { id: 98, label: "Mauritania", value: "MRT" },
  { id: 99, label: "Mauricio", value: "MUS" },
  { id: 100, label: "Malaui", value: "MWI" },
  { id: 101, label: "Malasia", value: "MYS" },
  { id: 102, label: "Namibia", value: "NAM" },
  { id: 103, label: "Nueva Caledonia", value: "NCL" },
  { id: 104, label: "Níger", value: "NER" },
  { id: 105, label: "Nigeria", value: "NGA" },
  { id: 106, label: "Nicaragua", value: "NIC" },
  { id: 107, label: "Países Bajos", value: "NLD" },
  { id: 108, label: "Noruega", value: "NOR" },
  { id: 109, label: "Nepal", value: "NPL" },
  { id: 110, label: "Nueva Zelanda", value: "NZL" },
  { id: 111, label: "Omán", value: "OMN" },
  { id: 112, label: "Pakistán", value: "PAK" },
  { id: 113, label: "Panamá", value: "PAN" },
  { id: 114, label: "Papúa Nueva Guinea", value: "PNG" },
  { id: 115, label: "Polonia", value: "POL" },
  { id: 116, label: "Portugal", value: "PRT" },
  { id: 117, label: "Catar", value: "QAT" },
  { id: 118, label: "Rumania", value: "ROU" },
  { id: 119, label: "Rusia", value: "RUS" },
  { id: 120, label: "Ruanda", value: "RWA" },
  { id: 121, label: "Arabia Saudita", value: "SAU" },
  { id: 122, label: "Senegal", value: "SEN" },
  { id: 123, label: "Singapur", value: "SGP" },
  { id: 124, label: "Sierra Leona", value: "SLE" },
  { id: 125, label: "El Salvador", value: "SLV" },
  { id: 126, label: "San Marino", value: "SMR" },
  { id: 127, label: "Somalia", value: "SOM" },
  { id: 128, label: "Surinam", value: "SUR" },
  { id: 129, label: "Eslovaquia", value: "SVK" },
  { id: 130, label: "Eslovenia", value: "SVN" },
  { id: 131, label: "Suecia", value: "SWE" },
  { id: 132, label: "Esuatini", value: "SWZ" },
  { id: 133, label: "Togo", value: "TGO" },
  { id: 134, label: "Tailandia", value: "THA" },
  { id: 135, label: "Tayikistán", value: "TJK" },
  { id: 136, label: "Timor Oriental", value: "TLS" },
  { id: 137, label: "Turquía", value: "TUR" },
  { id: 138, label: "Trinidad y Tobago", value: "TTO" },
  { id: 139, label: "Taiwán", value: "TWN" },
  { id: 140, label: "Túnez", value: "TUN" },
  { id: 141, label: "Ucrania", value: "UKR" },
  { id: 142, label: "Estados Unidos", value: "USA" },
  { id: 143, label: "Uruguay", value: "URY" },
  { id: 144, label: "Uzbekistán", value: "UZB" },
  { id: 145, label: "Vanuatu", value: "VUT" },
  { id: 146, label: "Venezuela", value: "VEN" },
  { id: 147, label: "Vietnam", value: "VNM" },
  { id: 148, label: "Perú", value: "PER" },
];
