import type { TypeOption } from "~/types/TypeOptions";

export const officeOptions: TypeOption[] = [
  { id: 1, label: "LIMA", name: "LIMA", value: "LIM", acronimo: "LIM" },
  {
    id: 2,
    label: "ABANCAY",
    name: "ABANCAY",
    value: "ABA",
    acronimo: "ABA",
  },
  {
    id: 3,
    label: "ANDAHUAYLAS",
    name: "ANDAHUAYLAS",
    value: "AND",
    acronimo: "AND",
  },
  {
    id: 4,
    label: "AREQUIPA",
    name: "AREQUIPA",
    value: "ARE",
    acronimo: "ARE",
  },
  {
    id: 5,
    label: "AYACUCHO",
    name: "AYACUCHO",
    value: "AYA",
    acronimo: "AYA",
  },
  { id: 6, label: "BAGUA", name: "BAGUA", value: "BAG", acronimo: "BAG" },
  {
    id: 7,
    label: "BARRANCA",
    name: "BARRANCA",
    value: "BAR",
    acronimo: "BAR",
  },
  {
    id: 8,
    label: "CAJAMARCA",
    name: "CAJAMARCA",
    value: "CAJ",
    acronimo: "CAJ",
  },
  { id: 9, label: "CALLAO", name: "CALLAO", value: "CAL", acronimo: "CAL" },
  { id: 10, label: "CAMANA", name: "CAMANA", value: "CAM", acronimo: "CAM" },
  { id: 11, label: "CASMA", name: "CASMA", value: "CAS", acronimo: "CAS" },
  {
    id: 12,
    label: "CASTILLA _ APLAO",
    name: "CASTILLA _ APLAO",
    value: "CAP",
    acronimo: "CAP",
  },
  { id: 13, label: "CAÑETE", name: "CAÑETE", value: "CAÑ", acronimo: "CAÑ" },
  {
    id: 14,
    label: "CHACHAPOYAS",
    name: "CHACHAPOYAS",
    value: "CHA",
    acronimo: "CHA",
  },
  { id: 15, label: "CHEPEN", name: "CHEPEN", value: "CHE", acronimo: "CHE" },
  {
    id: 16,
    label: "CHICLAYO",
    name: "CHICLAYO",
    value: "CHI",
    acronimo: "CHI",
  },
  {
    id: 17,
    label: "CHIMBOTE",
    name: "CHIMBOTE",
    value: "CHM",
    acronimo: "CHM",
  },
  {
    id: 18,
    label: "CHINCHA",
    name: "CHINCHA",
    value: "CHN",
    acronimo: "CHN",
  },
  { id: 19, label: "CHOTA", name: "CHOTA", value: "CHO", acronimo: "CHO" },
  { id: 20, label: "CUSCO", name: "CUSCO", value: "CUS", acronimo: "CUS" },
  {
    id: 21,
    label: "ESPINAR",
    name: "ESPINAR",
    value: "ESP",
    acronimo: "ESP",
  },
  { id: 22, label: "HUACHO", name: "HUACHO", value: "HUA", acronimo: "HUA" },
  {
    id: 23,
    label: "HUAMACHUCO",
    name: "HUAMACHUCO",
    value: "HUM",
    acronimo: "HUM",
  },
  {
    id: 24,
    label: "HUANCAVELICA",
    name: "HUANCAVELICA",
    value: "HUV",
    acronimo: "HUV",
  },
  {
    id: 25,
    label: "HUANCAYO",
    name: "HUANCAYO",
    value: "HUY",
    acronimo: "HUY",
  },
  { id: 26, label: "HUANTA", name: "HUANTA", value: "HUN", acronimo: "HUN" },
  {
    id: 27,
    label: "HUANUCO",
    name: "HUANUCO",
    value: "HUC",
    acronimo: "HUC",
  },
  { id: 28, label: "HUARAL", name: "HUARAL", value: "HUR", acronimo: "HUR" },
  { id: 29, label: "HUARAZ", name: "HUARAZ", value: "HZ", acronimo: "HZ" },
  { id: 30, label: "ICA", name: "ICA", value: "ICA", acronimo: "ICA" },
  { id: 31, label: "ILO", name: "ILO", value: "ILO", acronimo: "ILO" },
  {
    id: 32,
    label: "ISLAY _ MOLLENDO",
    name: "ISLAY _ MOLLENDO",
    value: "IMO",
    acronimo: "IMO",
  },
  { id: 33, label: "JAEN", name: "JAEN", value: "JAE", acronimo: "JAE" },
  {
    id: 34,
    label: "JUANJUI",
    name: "JUANJUI",
    value: "JUI",
    acronimo: "JUI",
  },
  {
    id: 35,
    label: "JULIACA",
    name: "JULIACA",
    value: "JUL",
    acronimo: "JUL",
  },
  {
    id: 36,
    label: "LA MERCED (SELVA CENTRAL)",
    name: "LA MERCED (SELVA CENTRAL)",
    value: "LMC",
    acronimo: "LMC",
  },
  {
    id: 37,
    label: "MADRE DE DIOS",
    name: "MADRE DE DIOS",
    value: "MDD",
    acronimo: "MDD",
  },
  { id: 38, label: "MAYNAS", name: "MAYNAS", value: "MAY", acronimo: "MAY" },
  {
    id: 39,
    label: "MOQUEGUA",
    name: "MOQUEGUA",
    value: "MOQ",
    acronimo: "MOQ",
  },
  {
    id: 40,
    label: "MOYOBAMBA",
    name: "MOYOBAMBA",
    value: "MOY",
    acronimo: "MOY",
  },
  { id: 41, label: "NAZCA", name: "NAZCA", value: "NAZ", acronimo: "NAZ" },
  { id: 42, label: "OTUZCO", name: "OTUZCO", value: "OTU", acronimo: "OTU" },
  { id: 43, label: "PASCO", name: "PASCO", value: "PAS", acronimo: "PAS" },
  { id: 44, label: "PISCO", name: "PISCO", value: "PIS", acronimo: "PIS" },
  { id: 45, label: "PIURA", name: "PIURA", value: "PIU", acronimo: "PIU" },
  {
    id: 46,
    label: "PUCALLPA",
    name: "PUCALLPA",
    value: "PUC",
    acronimo: "PUC",
  },
  { id: 47, label: "PUNO", name: "PUNO", value: "PUN", acronimo: "PUN" },
  {
    id: 48,
    label: "QUILLABAMBA",
    name: "QUILLABAMBA",
    value: "QUI",
    acronimo: "QUI",
  },
  {
    id: 49,
    label: "SAN PEDRO",
    name: "SAN PEDRO",
    value: "SPE",
    acronimo: "SPE",
  },
  { id: 50, label: "SATIPO", name: "SATIPO", value: "SAT", acronimo: "SAT" },
  {
    id: 51,
    label: "SICUANI",
    name: "SICUANI",
    value: "SIC",
    acronimo: "SIC",
  },
  {
    id: 52,
    label: "SULLANA",
    name: "SULLANA",
    value: "SUL",
    acronimo: "SUL",
  },
  { id: 53, label: "TACNA", name: "TACNA", value: "TAC", acronimo: "TAC" },
  {
    id: 54,
    label: "TARAPOTO",
    name: "TARAPOTO",
    value: "TAR",
    acronimo: "TAR",
  },
  { id: 55, label: "TARMA", name: "TARMA", value: "TAR", acronimo: "TAR" },
  {
    id: 56,
    label: "TINGO MARIA",
    name: "TINGO MARIA",
    value: "TIN",
    acronimo: "TIN",
  },
  {
    id: 57,
    label: "TRUJILLO",
    name: "TRUJILLO",
    value: "TRU",
    acronimo: "TRU",
  },
  { id: 58, label: "TUMBES", name: "TUMBES", value: "TUM", acronimo: "TUM" },
  {
    id: 59,
    label: "YURIMAGUAS",
    name: "YURIMAGUAS",
    value: "YUR",
    acronimo: "YUR",
  },
];
