import type { TypeOption } from "~/types/TypeOptions";

export const officeOptions: TypeOption[] = [
  { id: 1, label: "LIMA", name: "LIMA", value: "LIMA", acronimo: "LIM" },
  {
    id: 2,
    label: "ABANCAY",
    name: "ABANCAY",
    value: "ABANCAY",
    acronimo: "ABA",
  },
  {
    id: 3,
    label: "ANDAHUAYLAS",
    name: "ANDAHUAYLAS",
    value: "ANDAHUAYLAS",
    acronimo: "AND",
  },
  {
    id: 4,
    label: "AREQUIPA",
    name: "AREQUIPA",
    value: "AREQUIPA",
    acronimo: "ARE",
  },
  {
    id: 5,
    label: "AYACUCHO",
    name: "AYACUCHO",
    value: "AYACUCHO",
    acronimo: "AYA",
  },
  { id: 6, label: "BAGUA", name: "BAGUA", value: "BAGUA", acronimo: "BAG" },
  {
    id: 7,
    label: "BARRANCA",
    name: "BARRANCA",
    value: "BARRANCA",
    acronimo: "BAR",
  },
  {
    id: 8,
    label: "CAJAMARCA",
    name: "CAJAMARCA",
    value: "CAJAMARCA",
    acronimo: "CAJ",
  },
  { id: 9, label: "CALLAO", name: "CALLAO", value: "CALLAO", acronimo: "CAL" },
  { id: 10, label: "CAMANA", name: "CAMANA", value: "CAMANA", acronimo: "CAM" },
  { id: 11, label: "CASMA", name: "CASMA", value: "CASMA", acronimo: "CAS" },
  {
    id: 12,
    label: "CASTILLA _ APLAO",
    name: "CASTILLA _ APLAO",
    value: "CASTILLA _ APLAO",
    acronimo: "CAP",
  },
  { id: 13, label: "CAÑETE", name: "CAÑETE", value: "CAÑETE", acronimo: "CAÑ" },
  {
    id: 14,
    label: "CHACHAPOYAS",
    name: "CHACHAPOYAS",
    value: "CHACHAPOYAS",
    acronimo: "CHA",
  },
  { id: 15, label: "CHEPEN", name: "CHEPEN", value: "CHEPEN", acronimo: "CHE" },
  {
    id: 16,
    label: "CHICLAYO",
    name: "CHICLAYO",
    value: "CHICLAYO",
    acronimo: "CHI",
  },
  {
    id: 17,
    label: "CHIMBOTE",
    name: "CHIMBOTE",
    value: "CHIMBOTE",
    acronimo: "CHM",
  },
  {
    id: 18,
    label: "CHINCHA",
    name: "CHINCHA",
    value: "CHINCHA",
    acronimo: "CHN",
  },
  { id: 19, label: "CHOTA", name: "CHOTA", value: "CHOTA", acronimo: "CHO" },
  { id: 20, label: "CUSCO", name: "CUSCO", value: "CUSCO", acronimo: "CUS" },
  {
    id: 21,
    label: "ESPINAR",
    name: "ESPINAR",
    value: "ESPINAR",
    acronimo: "ESP",
  },
  { id: 22, label: "HUACHO", name: "HUACHO", value: "HUACHO", acronimo: "HUA" },
  {
    id: 23,
    label: "HUAMACHUCO",
    name: "HUAMACHUCO",
    value: "HUAMACHUCO",
    acronimo: "HUM",
  },
  {
    id: 24,
    label: "HUANCAVELICA",
    name: "HUANCAVELICA",
    value: "HUANCAVELICA",
    acronimo: "HUV",
  },
  {
    id: 25,
    label: "HUANCAYO",
    name: "HUANCAYO",
    value: "HUANCAYO",
    acronimo: "HUY",
  },
  { id: 26, label: "HUANTA", name: "HUANTA", value: "HUANTA", acronimo: "HUN" },
  {
    id: 27,
    label: "HUANUCO",
    name: "HUANUCO",
    value: "HUANUCO",
    acronimo: "HUC",
  },
  { id: 28, label: "HUARAL", name: "HUARAL", value: "HUARAL", acronimo: "HUR" },
  { id: 29, label: "HUARAZ", name: "HUARAZ", value: "HUARAZ", acronimo: "HZ" },
  { id: 30, label: "ICA", name: "ICA", value: "ICA", acronimo: "ICA" },
  { id: 31, label: "ILO", name: "ILO", value: "ILO", acronimo: "ILO" },
  {
    id: 32,
    label: "ISLAY _ MOLLENDO",
    name: "ISLAY _ MOLLENDO",
    value: "ISLAY _ MOLLENDO",
    acronimo: "IMO",
  },
  { id: 33, label: "JAEN", name: "JAEN", value: "JAEN", acronimo: "JAE" },
  {
    id: 34,
    label: "JUANJUI",
    name: "JUANJUI",
    value: "JUANJUI",
    acronimo: "JUI",
  },
  {
    id: 35,
    label: "JULIACA",
    name: "JULIACA",
    value: "JULIACA",
    acronimo: "JUL",
  },
  {
    id: 36,
    label: "LA MERCED (SELVA CENTRAL)",
    name: "LA MERCED (SELVA CENTRAL)",
    value: "LA MERCED (SELVA CENTRAL)",
    acronimo: "LMC",
  },
  {
    id: 37,
    label: "MADRE DE DIOS",
    name: "MADRE DE DIOS",
    value: "MADRE DE DIOS",
    acronimo: "MDD",
  },
  { id: 38, label: "MAYNAS", name: "MAYNAS", value: "MAYNAS", acronimo: "MAY" },
  {
    id: 39,
    label: "MOQUEGUA",
    name: "MOQUEGUA",
    value: "MOQUEGUA",
    acronimo: "MOQ",
  },
  {
    id: 40,
    label: "MOYOBAMBA",
    name: "MOYOBAMBA",
    value: "MOYOBAMBA",
    acronimo: "MOY",
  },
  { id: 41, label: "NAZCA", name: "NAZCA", value: "NAZCA", acronimo: "NAZ" },
  { id: 42, label: "OTUZCO", name: "OTUZCO", value: "OTUZCO", acronimo: "OTU" },
  { id: 43, label: "PASCO", name: "PASCO", value: "PASCO", acronimo: "PAS" },
  { id: 44, label: "PISCO", name: "PISCO", value: "PISCO", acronimo: "PIS" },
  { id: 45, label: "PIURA", name: "PIURA", value: "PIURA", acronimo: "PIU" },
  {
    id: 46,
    label: "PUCALLPA",
    name: "PUCALLPA",
    value: "PUCALLPA",
    acronimo: "PUC",
  },
  { id: 47, label: "PUNO", name: "PUNO", value: "PUNO", acronimo: "PUN" },
  {
    id: 48,
    label: "QUILLABAMBA",
    name: "QUILLABAMBA",
    value: "QUILLABAMBA",
    acronimo: "QUI",
  },
  {
    id: 49,
    label: "SAN PEDRO",
    name: "SAN PEDRO",
    value: "SAN PEDRO",
    acronimo: "SPE",
  },
  { id: 50, label: "SATIPO", name: "SATIPO", value: "SATIPO", acronimo: "SAT" },
  {
    id: 51,
    label: "SICUANI",
    name: "SICUANI",
    value: "SICUANI",
    acronimo: "SIC",
  },
  {
    id: 52,
    label: "SULLANA",
    name: "SULLANA",
    value: "SULLANA",
    acronimo: "SUL",
  },
  { id: 53, label: "TACNA", name: "TACNA", value: "TACNA", acronimo: "TAC" },
  {
    id: 54,
    label: "TARAPOTO",
    name: "TARAPOTO",
    value: "TARAPOTO",
    acronimo: "TAR",
  },
  { id: 55, label: "TARMA", name: "TARMA", value: "TARMA", acronimo: "TAR" },
  {
    id: 56,
    label: "TINGO MARIA",
    name: "TINGO MARIA",
    value: "TINGO MARIA",
    acronimo: "TIN",
  },
  {
    id: 57,
    label: "TRUJILLO",
    name: "TRUJILLO",
    value: "TRUJILLO",
    acronimo: "TRU",
  },
  { id: 58, label: "TUMBES", name: "TUMBES", value: "TUMBES", acronimo: "TUM" },
  {
    id: 59,
    label: "YURIMAGUAS",
    name: "YURIMAGUAS",
    value: "YURIMAGUAS",
    acronimo: "YUR",
  },
];
